const weapons = [
    "none",
    "missile_alien_pod",
    "missile_creeper",
    "missile_devastator",
    "missile_devastator_mini",
    "missile_falcon",
    "missile_hunter",
    "missile_pod",
    "missile_smart",
    "missile_smart_mini",
    "missile_timebomb",
    "missile_vortex",
    "proj_alien_blaster",
    "proj_alien_vulcan",
    "proj_beam",
    "proj_driller",
    "proj_driller_mini",
    "proj_enemy_blaster",
    "proj_enemy_core",
    "proj_enemy_vulcan",
    "proj_flak_cannon",
    "proj_flare",
    "proj_flare_sticky",
    "proj_impulse",
    "proj_melee",
    "proj_reflex",
    "proj_shotgun",
    "proj_thunderbolt",
    "proj_vortex",
    "num"
];

const weaponNames = [
    "Miscellaneous",
    "Unknown",
    "Creeper",
    "Devastator",
    "Devastator",
    "Falcon",
    "Hunter",
    "Missile Pod",
    "Nova",
    "Nova",
    "Time Bomb",
    "Vortex",
    "Unknown",
    "Unknown",
    "Lancer",
    "Driller",
    "Unknown",
    "Unknown",
    "Unknown",
    "Unknown",
    "Flak",
    "Flare",
    "Unknown",
    "Impulse",
    "Unknown",
    "Reflex",
    "Crusher",
    "Thunderbolt",
    "Cyclone",
    "Unknown"
];

const orderedWeapons = [
    "Impulse",
    "Cyclone",
    "Reflex",
    "Crusher",
    "Driller",
    "Flak",
    "Thunderbolt",
    "Lancer",
    "Falcon",
    "Missile Pod",
    "Hunter",
    "Creeper",
    "Nova",
    "Devastator",
    "Time Bomb",
    "Vortex",
    "Flare",
    "Miscellaneous",
    "Unknown"
];

module.exports = {
    weapons,
    weaponNames,
    orderedWeapons
};
